import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 
  | 'en' 
  | 'hi' 
  | 'ta' 
  | 'te' 
  | 'kn' 
  | 'ml' 
  | 'mr'
  | 'as' 
  | 'bn' 
  | 'mni' 
  | 'lus' 
  | 'brx' 
  | 'kha';

interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  category: 'Universal / National' | 'North Eastern Region';
}

export const LANGUAGES: LanguageOption[] = [
  // Universal / National Indian Languages
  { code: 'en', name: 'English', nativeName: 'English', flag: '🌐', category: 'Universal / National' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', category: 'Universal / National' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🪔', category: 'Universal / National' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🏛️', category: 'Universal / National' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🌸', category: 'Universal / National' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🌴', category: 'Universal / National' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🚩', category: 'Universal / National' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🪷', category: 'Universal / National' },
  
  // North Eastern Region Languages
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🌾', category: 'North Eastern Region' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্', flag: '🏔️', category: 'North Eastern Region' },
  { code: 'lus', name: 'Mizo', nativeName: 'Mizo ṭawng', flag: '🌿', category: 'North Eastern Region' },
  { code: 'brx', name: 'Bodo', nativeName: 'बर\'', flag: '🌲', category: 'North Eastern Region' },
  { code: 'kha', name: 'Khasi', nativeName: 'Ka Ktien Khasi', flag: '⛰️', category: 'North Eastern Region' }
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    app_title: 'LOGAINER',
    app_subtitle: 'AI Logistics & Accessibility Platform for North Eastern Region',
    gis_map: 'GIS Map Center',
    route_optimizer: 'Route Optimizer',
    route_planner: 'Route Optimizer',
    fleet_telemetry: 'Live Fleet Telemetry',
    district_connectivity: 'District Connectivity Index',
    district_health: 'District Connectivity Index',
    incident_monitoring: 'Incident Monitoring',
    incident_reporter: 'Incident Monitoring',
    ai_risk_prediction: 'AI Risk Prediction',
    ml_risk_lab: 'AI Risk Prediction',
    disaster_mode: 'Disaster Emergency Mode',
    logistics_monitoring: 'Logistics Monitoring',
    alerts_notifications: 'Alerts & Notifications',
    analytics_reports: 'Reports & Analytics',
    user_vehicle_mgmt: 'User & Vehicle Management',
    all_states: 'All 8 NER States',
    active_convoys: 'Active Convoys',
    chokepoints_blocked: 'Chokepoints Blocked',
    avg_dci: 'Average DCI Index',
    ai_risk_status: 'AI Hazard Index',
    report_obstacle: 'Report Road Blockage',
    simulate_red_alert: 'SIMULATE RED ALERT',
    reset_alert: 'Reset Emergency Alert',
    audio_broadcast: 'Voice Alert Broadcast',
    online_satellite: 'Network: Multi-Sat + 5G Active',
    offline_mode: 'Offline Storage Active',
    origin: 'Origin Logistics Hub',
    destination: 'Destination Node',
    calculate_route: 'Compute AI Optimized Routes',
    speed: 'Speed',
    temp: 'Cold-Chain Temp',
    driver: 'Driver',
    cargo: 'Cargo',
    sos_trigger: 'TRIGGER DRIVER SOS',
    verified: 'Verified Official',
    disaster_active: 'EMERGENCY RED ALERT ACTIVE ACROSS NER CORRIDORS',
    sync_now: 'Sync Offline Records',
    command_modules: 'Command Modules',
    active_fleets: 'Active Fleets',
    deficit_districts: 'Deficit Districts'
  },
  ta: {
    app_title: 'லோகைனர் (LOGAINER)',
    app_subtitle: 'வடகிழக்கு பிராந்தியத்திற்கான AI சரக்கு போக்குவரத்து & வழித்தட நுண்ணறிவு தளம்',
    gis_map: 'GIS வரைபட மையம்',
    route_planner: 'AI வழித்தட உகப்பாக்கி',
    fleet_telemetry: 'நேரலை வாகன கண்காணிப்பு',
    district_health: 'மாவட்ட இணைப்பு குறியீடு (DCI)',
    incident_reporter: 'கள இடர்பாடு அறிக்கை',
    ml_risk_lab: 'AI நிலச்சரிவு முன்னறிவிப்பு',
    disaster_mode: 'பேரிடர் அவசரகால பயன்முறை',
    analytics_reports: 'அரசு தொழில்நுட்ப அறிக்கைகள்',
    all_states: 'அனைத்து 8 வடகிழக்கு மாநிலங்கள்',
    active_convoys: 'இயங்கும் வாகனங்கள்',
    chokepoints_blocked: 'தடைபட்ட பாதைகள்',
    avg_dci: 'சராசரி இணைப்பு குறியீடு',
    ai_risk_status: 'AI ஆபத்து குறியீடு',
    report_obstacle: 'சாலை அடைப்பை பதிவுசெய்',
    simulate_red_alert: 'சிவப்பு எச்சரிக்கை தொடங்கு',
    reset_alert: 'எச்சரிக்கையை மீட்டமை',
    audio_broadcast: 'குரல்வழி எச்சரிக்கை ஒளிபரப்பு',
    online_satellite: 'நெட்வொர்க்: செயற்கைக்கோள் + 5G செயலில்',
    offline_mode: 'ஆஃப்லைன் சேமிப்பு செயலில்',
    origin: 'தொடக்க சரக்கு மையம்',
    destination: 'சேருமிடம்',
    calculate_route: 'AI உகந்த பாதையைக் கணக்கிடு',
    speed: 'வேகம்',
    temp: 'குளிர்பதன வெப்பநிலை',
    driver: 'ஓட்டுநர்',
    cargo: 'சரக்கு',
    sos_trigger: 'அவசர SOS அனுப்பு',
    verified: 'அதிகாரப்பூர்வமாக சரிபார்க்கப்பட்டது',
    disaster_active: 'வடகிழக்கு நெடுஞ்சாலைகளில் அவசரகால சிவப்பு எச்சரிக்கை செயலில் உள்ளது',
    sync_now: 'ஆஃப்லைன் பதிவுகளை ஒத்திசை',
    command_modules: 'கட்டுப்பாட்டு தொகுதிகள்',
    active_fleets: 'செயலில் உள்ள வாகனங்கள்',
    deficit_districts: 'பற்றாக்குறை மாவட்டங்கள்'
  },
  te: {
    app_title: 'లాగైనర్ (LOGAINER)',
    app_subtitle: 'ఈశాన్య ప్రాంతం కోసం AI లాజిస్టిక్స్ & యాక్సెసిబిలిటీ ఇంటెలిజెన్స్ ప్లాట్‌ఫారమ్',
    gis_map: 'GIS మ్యాప్ కేంద్రం',
    route_planner: 'AI రూట్ ఆప్టిమైజర్',
    fleet_telemetry: 'లైవ్ వెహికల్ ట్రాకింగ్',
    district_health: 'జిల్లా కనెక్టివిటీ సూచిక (DCI)',
    incident_reporter: 'ఫీల్డ్ ఇన్సిడెంట్ రిపోర్ట్',
    ml_risk_lab: 'AI కొండచరియల అంచనా',
    disaster_mode: 'విపత్తు అత్యవసర మోడ్',
    analytics_reports: 'ప్రభుత్వ నివేదికలు',
    all_states: 'అన్ని 8 ఈశాన్య రాష్ట్రాలు',
    active_convoys: 'యాక్టివ్ వాహనాలు',
    chokepoints_blocked: 'మూసివేసిన మార్గాలు',
    avg_dci: 'సగటు కనెక్టివిటీ సూచిక',
    ai_risk_status: 'AI ప్రమాద సూచిక',
    report_obstacle: 'రోడ్డు అడ్డంకిని నివేదించండి',
    simulate_red_alert: 'రెడ్ అలర్ట్ ప్రారంభించండి',
    reset_alert: 'అలర్ట్‌ను రీసెట్ చేయండి',
    audio_broadcast: 'వాయిస్ అలర్ట్ ప్రసారం',
    online_satellite: 'నెట్‌వర్క్: ఉపగ్రహం + 5G యాక్టివ్',
    offline_mode: 'ఆఫ్‌లైన్ నిల్వ యాక్టివ్',
    origin: 'ప్రారంభ లాజిస్టిక్స్ హబ్',
    destination: 'గమ్యస్థానం',
    calculate_route: 'AI మార్గాన్ని లెక్కించండి',
    speed: 'వేగం',
    temp: 'కోల్డ్ చైన్ ఉష్ణోగ్రత',
    driver: 'డ్రైవర్',
    cargo: 'సరుకు',
    sos_trigger: 'అత్యవసర SOS పంపండి',
    verified: 'అధికారికంగా ధృవీకరించబడింది',
    disaster_active: 'ఈశాన్య హైవేలలో అత్యవసర రెడ్ అలర్ట్ యాక్టివ్‌గా ఉంది',
    sync_now: 'ఆఫ్‌లైన్ డేటాను సింక్ చేయండి',
    command_modules: 'కమాండ్ మాడ్యూల్స్',
    active_fleets: 'యాక్టివ్ వాహనాలు',
    deficit_districts: 'కొరత జిల్లాలు'
  },
  kn: {
    app_title: 'ಲಾಗೈನರ್ (LOGAINER)',
    app_subtitle: 'ಈಶಾನ್ಯ ಪ್ರದೇಶಕ್ಕಾಗಿ AI ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಮತ್ತು ಪ್ರವೇಶಿಸುವಿಕೆ ಗುಪ್ತಚರ ವೇದಿಕೆ',
    gis_map: 'GIS ನಕ್ಷೆ ಕೇಂದ್ರ',
    route_planner: 'AI ಮಾರ್ಗ ಆಪ್ಟಿಮೈಜರ್',
    fleet_telemetry: 'ಲೈವ್ ವಾಹನ ಟ್ರ್ಯಾಕಿಂಗ್',
    district_health: 'ಜಿಲ್ಲಾ ಸಂಪರ್ಕ ಸೂಚ್ಯಂಕ (DCI)',
    incident_reporter: 'ಕ್ಷೇತ್ರ ಘಟನೆ ವರದಿ',
    ml_risk_lab: 'AI ಭೂಕುಸಿತ ಮುನ್ಸೂಚನೆ',
    disaster_mode: 'ವಿಪತ್ತು ತುರ್ತು ಮೋಡ್',
    analytics_reports: 'ಸರ್ಕಾರಿ ವರದಿಗಳು',
    all_states: 'ಎಲ್ಲಾ 8 ಈಶಾನ್ಯ ರಾಜ್ಯಗಳು',
    active_convoys: 'ಸಕ್ರಿಯ ವಾಹನಗಳು',
    chokepoints_blocked: 'ನಿರ್ಬಂಧಿತ ಮಾರ್ಗಗಳು',
    avg_dci: 'ಸರಾಸರಿ ಸಂಪರ್ಕ ಸೂಚ್ಯಂಕ',
    ai_risk_status: 'AI ಅಪಾಯದ ಸೂಚ್ಯಂಕ',
    report_obstacle: 'ರಸ್ತೆ ಅಡೆತಡೆ ವರದಿ ಮಾಡಿ',
    simulate_red_alert: 'ರೆಡ್ ಅಲರ್ಟ್ ಪ್ರಾರಂಭಿಸಿ',
    reset_alert: 'ಅಲರ್ಟ್ ಮರುಹೊಂದಿಸಿ',
    audio_broadcast: 'ಧ್ವನಿ ಎಚ್ಚರಿಕೆ ಪ್ರಸಾರ',
    online_satellite: 'ನೆಟ್‌ವರ್ಕ್: ಸಕ್ರಿಯ',
    offline_mode: 'ಆಫ್‌ಲೈನ್ ಸಂಗ್ರಹಣೆ ಸಕ್ರಿಯ',
    origin: 'ಆರಂಭಿಕ ಹಬ್',
    destination: 'ಗಮ್ಯಸ್ಥಾನ',
    calculate_route: 'AI ಮಾರ್ಗ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ',
    speed: 'ವೇಗ',
    temp: 'ಕೋಲ್ಡ್ ಚೈನ್ ತಾಪಮಾನ',
    driver: 'ಚಾಲಕ',
    cargo: 'ಸರಕು',
    sos_trigger: 'ತುರ್ತು SOS ಕಳುಹಿಸಿ',
    verified: 'ಅಧಿಕೃತವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    disaster_active: 'ಈಶಾನ್ಯ ಹೆದ್ದಾರಿಗಳಲ್ಲಿ ತುರ್ತು ರೆಡ್ ಅಲರ್ಟ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    sync_now: 'ಆಫ್‌ಲೈನ್ ಡೇಟಾ ಸಿಂಕ್ ಮಾಡಿ',
    command_modules: 'ಕಮಾಂಡ್ ಮಾಡ್ಯೂಲ್‌ಗಳು',
    active_fleets: 'ಸಕ್ರಿಯ ವಾಹನಗಳು',
    deficit_districts: 'ಕೊರತೆಯಿರುವ ಜಿಲ್ಲೆಗಳು'
  },
  ml: {
    app_title: 'ലോഗൈനർ (LOGAINER)',
    app_subtitle: 'വടക്കുകിഴക്കൻ മേഖലയ്ക്കായുള്ള AI ലോജിസ്റ്റിക്സ് പ്ലാറ്റ്‌ഫോം',
    gis_map: 'ജിഐഎസ് മാപ്പ് സെന്റർ',
    route_planner: 'AI റൂട്ട് ഒപ്റ്റിമൈസർ',
    fleet_telemetry: 'ലൈവ് വാഹനം ട്രാക്കിംഗ്',
    district_health: 'ജില്ലാ കണക്റ്റിവിറ്റി സൂചിക (DCI)',
    incident_reporter: 'ഫീൽഡ് ഇൻസിഡന്റ് റിപ്പോർട്ട്',
    ml_risk_lab: 'AI മണ്ണിടിച്ചിൽ പ്രവചനം',
    disaster_mode: 'ദുരന്ത നിവാരണ എമർജൻസി മോഡ്',
    analytics_reports: 'ഗവൺമെന്റ് റിപ്പോർട്ടുകൾ',
    all_states: 'എല്ലാ 8 വടക്കുകിഴക്കൻ സംസ്ഥാനങ്ങളും',
    active_convoys: 'സജീവ വാഹനങ്ങൾ',
    chokepoints_blocked: 'തടസ്സപ്പെട്ട പാതകൾ',
    avg_dci: 'ശരാശരി കണക്റ്റിവിറ്റി സൂചിക',
    ai_risk_status: 'AI അപകട സൂചിക',
    report_obstacle: 'റോഡ് തടസ്സം റിപ്പോർട്ട് ചെയ്യുക',
    simulate_red_alert: 'റെഡ് അലർട്ട് ആരംഭിക്കുക',
    reset_alert: 'അലർട്ട് റീസെറ്റ് ചെയ്യുക',
    audio_broadcast: 'ശബ്ദ മുന്നറിയിപ്പ് പ്രക്ഷേപണം',
    online_satellite: 'നെറ്റ്‌വർക്ക്: സജീവം',
    offline_mode: 'ഓഫ്‌ലൈൻ സംഭരണം സജീവം',
    origin: 'ഉത്ഭവ ഹബ്ബ്',
    destination: 'ലക്ഷ്യസ്ഥാനം',
    calculate_route: 'AI റൂട്ട് കണക്കാക്കുക',
    speed: 'വേഗത',
    temp: 'ശീതീകരിച്ച താപനില',
    driver: 'ഡ്രൈവർ',
    cargo: 'സാധനങ്ങൾ',
    sos_trigger: 'അടിയന്തര SOS അയക്കുക',
    verified: 'ഔദ്യോഗികമായി സ്ഥിരീകരിച്ചു',
    disaster_active: 'വടക്കുകിഴക്കൻ ഹൈവേകളിൽ അടിയന്തര റെഡ് അലർട്ട് നിലവിലുണ്ട്',
    sync_now: 'ഓഫ്‌ലൈൻ ഡാറ്റ സമന്വയിപ്പിക്കുക',
    command_modules: 'കമാൻഡ് മൊഡ്യൂളുകൾ',
    active_fleets: 'സജീവ വാഹനങ്ങൾ',
    deficit_districts: 'ക്ഷാമമുള്ള ജില്ലകൾ'
  },
  mr: {
    app_title: 'लॉगेनर (LOGAINER)',
    app_subtitle: 'ईशान्य भारतासाठी AI-आधारित लॉजिस्टिक्स आणि मार्ग बुद्धिमत्ता प्रणाली',
    gis_map: 'जीआयएस नकाशा केंद्र',
    route_planner: 'AI मार्ग ऑप्टिमायझर',
    fleet_telemetry: 'थेट वाहन ट्रॅकिंग',
    district_health: 'जिल्हा कनेक्टिव्हिटी निर्देशांक (DCI)',
    incident_reporter: 'घटना नोंदणी अहवाल',
    ml_risk_lab: 'AI भूस्खलन अंदाज',
    disaster_mode: 'आपत्ती आणीबाणी मोड',
    analytics_reports: 'सरकारी अहवाल',
    all_states: 'सर्व ८ ईशान्य राज्ये',
    active_convoys: 'सक्रिय वाहने',
    chokepoints_blocked: 'अवरोधित रस्ते',
    avg_dci: 'सरासरी कनेक्टिव्हिटी निर्देशांक',
    ai_risk_status: 'AI धोका निर्देशांक',
    report_obstacle: 'रस्ता अडथळा कळवा',
    simulate_red_alert: 'रेड अलर्ट सुरू करा',
    reset_alert: 'अलर्ट रीसेट करा',
    audio_broadcast: 'ध्वनी इशारा प्रसारण',
    online_satellite: 'नेटवर्क: सक्रिय',
    offline_mode: 'ऑफलाइन स्टोरेज सक्रिय',
    origin: 'सुरुवात हब',
    destination: 'गंतव्य स्थान',
    calculate_route: 'मार्ग मोजा',
    speed: 'वेग',
    temp: 'कोल्ड चेन तापमान',
    driver: 'चालक',
    cargo: 'माल',
    sos_trigger: 'आणीबाणी SOS पाठवा',
    verified: 'अधिकृत पडताळणी',
    disaster_active: 'ईशान्य महामार्गांवर आणीबाणीचा रेड अलर्ट सक्रिय',
    sync_now: 'ऑफलाइन डेटा सिंक करा',
    command_modules: 'कमांड मॉड्यूल्स',
    active_fleets: 'सक्रिय वाहने',
    deficit_districts: 'तुटवडा असलेले जिल्हे'
  },
  hi: {
    app_title: 'LOGAINER',
    app_subtitle: 'पूर्वोत्तर क्षेत्र (NER) के लिए AI-आधारित लॉजिस्टिक्स एवं पहुंच बुद्धिमत्ता प्रणाली',
    gis_map: 'जीआईएस मानचित्र केंद्र',
    route_planner: 'एआई मार्ग अनुकूलक',
    fleet_telemetry: 'लाइव वाहन ट्रैकिंग',
    district_health: 'जिला कनेक्टिविटी सूचकांक',
    incident_reporter: 'क्षेत्रीय घटना रिपोर्ट',
    ml_risk_lab: 'एआई भूस्खलन पूर्वसूचक',
    disaster_mode: 'आपदा आपातकालीन मोड',
    analytics_reports: 'सरकारी रिपोर्ट',
    all_states: 'सभी 8 पूर्वोत्तर राज्य',
    active_convoys: 'सक्रिय वाहन',
    chokepoints_blocked: 'अवरुद्ध मार्ग',
    avg_dci: 'औसत कनेक्टिविटी सूचकांक',
    ai_risk_status: 'एआई आपदा जोखिम',
    report_obstacle: 'सड़क अवरोध रिपोर्ट करें',
    simulate_red_alert: 'रेड अलर्ट सिमुलेशन',
    reset_alert: 'आपातकालीन अलर्ट रीसेट करें',
    audio_broadcast: 'ध्वनि चेतावनी प्रसारण',
    online_satellite: 'नेटवर्क: सक्रिय',
    offline_mode: 'ऑफ़लाइन संग्रहण सक्रिय',
    origin: 'प्रस्थान हब',
    destination: 'गंतव्य नोड',
    calculate_route: 'मार्ग की गणना करें',
    speed: 'गति',
    temp: 'कोल्ड चेन तापमान',
    driver: 'चालक',
    cargo: 'सामग्री',
    sos_trigger: 'एसओएस आपातकालीन अलर्ट',
    verified: 'आधिकारिक सत्यापित',
    disaster_active: 'पूर्वोत्तर राजमार्गों पर आपातकालीन रेड अलर्ट सक्रिय',
    sync_now: 'ऑफ़लाइन डेटा सिंक करें',
    command_modules: 'कमांड मॉड्यूल',
    active_fleets: 'सक्रिय वाहन',
    deficit_districts: 'कमी वाले जिले'
  },
  as: {
    app_title: 'লগাইনাৰ (LOGAINER)',
    app_subtitle: 'উত্তৰ-পূৰ্বাঞ্চলৰ বাবে AI ভিত্তিক স্মাৰ্ট পৰিবহণ আৰু পথ সুগমতা মঞ্চ',
    gis_map: 'GIS মানচিত্ৰ কেন্দ্ৰ',
    route_planner: 'AI পথ নিৰ্ধাৰক',
    fleet_telemetry: 'সক্ৰিয় বাহন ট্ৰেকিং',
    district_health: 'জিলা সংযোগ সূচক',
    incident_reporter: 'ঘটনাৰ প্ৰতিবেদন',
    ml_risk_lab: 'ভূমিস্খলন পূৰ্বানুমান',
    disaster_mode: 'জৰুৰীকালীন সাহায্য মোড',
    analytics_reports: 'চৰকাৰী প্ৰতিবেদন',
    all_states: 'উত্তৰ-পূবৰ ৮ খন ৰাজ্য',
    active_convoys: 'সক্ৰিয় বাহন',
    chokepoints_blocked: 'বন্ধ হোৱা পথ',
    avg_dci: 'গড় সংযোগ সূচক',
    ai_risk_status: 'AI বিপদ মাত্ৰা',
    report_obstacle: 'পথৰ অৱৰোধ জনোৱাক',
    simulate_red_alert: 'ৰেড এলাৰ্ট আৰম্ভ কৰক',
    reset_alert: 'এলাৰ্ট বন্ধ কৰক',
    audio_broadcast: 'ধ্বনি সঁহাৰি',
    online_satellite: 'নেটৱৰ্ক: সংযোগ আছে',
    offline_mode: 'অফলাইন জমা হৈছে',
    origin: 'আৰম্ভণি স্থান',
    destination: 'গন্তব্য স্থান',
    calculate_route: 'পথ গণনা কৰক',
    speed: 'গতিবেগ',
    temp: 'শীতল ভঁৰালৰ উষ্ণতা',
    driver: 'চালক',
    cargo: 'সামগ্ৰী',
    sos_trigger: 'জৰুৰীকালীন SOS',
    verified: 'প্ৰমাণিত তথ্য',
    disaster_active: 'উত্তৰ-পূবৰ ৰাষ্ট্ৰীয় ঘাইপথত জৰুৰী সতৰ্কতা জাৰি',
    sync_now: 'অফলাইন তথ্য আপলোড কৰক',
    command_modules: 'কমাণ্ড মডিউলসমূহ',
    active_fleets: 'সক্ৰিয় বাহন',
    deficit_districts: 'অভাৱী জিলাসমূহ'
  },
  bn: {
    app_title: 'লগেইনার (LOGAINER)',
    app_subtitle: 'উত্তর-পূর্ব ভারতের জন্য এআই-চালিত লজিস্টিক ও অ্যাক্সেসিবিলিটি প্ল্যাটফর্ম',
    gis_map: 'জিআইএস ম্যাপ সেন্টার',
    route_planner: 'এআই রুট অপ্টিমাইজার',
    fleet_telemetry: 'লাইভ ভেহিকল ট্র্যাকিং',
    district_health: 'জেলা কানেক্টিভিটি সূচক',
    incident_reporter: 'ঘটনার বিবরণ দাখিল',
    ml_risk_lab: 'ভূমিধস পূর্বাভাস',
    disaster_mode: 'জরুরী দুর্যোগ মোড',
    analytics_reports: 'সরকারি রিপোর্ট',
    all_states: '৮টি উত্তর-পূর্ব রাজ্য',
    active_convoys: 'সক্রিয় কনভয়',
    chokepoints_blocked: 'অবরুদ্ধ পথ',
    avg_dci: 'গড় সংযোগ সূচক',
    ai_risk_status: 'এআই ঝুঁকি সূচক',
    report_obstacle: 'রাস্তার বাধা জানান',
    simulate_red_alert: 'রেড অ্যালার্ট শুরু করুন',
    reset_alert: 'অ্যালার্ট বন্ধ করুন',
    audio_broadcast: 'ভয়েস অ্যালার্ট',
    online_satellite: 'নেটওয়ার্ক: সক্রিয়',
    offline_mode: 'অফলাইন মোড চালু',
    origin: 'উৎস হাব',
    destination: 'গন্তব্য স্থান',
    calculate_route: 'রুট গণনা করুন',
    speed: 'গতি',
    temp: 'কোল্ড চেইন তাপমাত্রা',
    driver: 'ড্রাইভার',
    cargo: 'পণ্য',
    sos_trigger: 'জরুরী এসওএস পাঠান',
    verified: 'অফিসিয়াল ভেরিফাইড',
    disaster_active: 'উত্তর-পূর্বের হাইওয়েতে দুর্যোগকালীন রেড অ্যালার্ট সক্রিয়',
    sync_now: 'অফলাইন ডেটা সিঙ্ক করুন',
    command_modules: 'কমান্ড মডিউল',
    active_fleets: 'সক্রিয় যানবাহন',
    deficit_districts: 'ঘাটতি জেলা'
  },
  mni: {
    app_title: 'LOGAINER',
    app_subtitle: 'North East Region AI Logistics & Accessibility Intelligence',
    gis_map: 'GIS Map Center',
    route_planner: 'AI Lambi Optimization',
    fleet_telemetry: 'Live Gari Tracking',
    district_health: 'District Connectivity Index',
    incident_reporter: 'Incident Report Tourou',
    ml_risk_lab: 'Landslide Forecast AI',
    disaster_mode: 'Emergency Disaster Mode',
    analytics_reports: 'Government Reports',
    all_states: 'NER State 8',
    active_convoys: 'Gari Chatliba',
    chokepoints_blocked: 'Lambi Thengliba',
    avg_dci: 'Avg Connectivity',
    ai_risk_status: 'AI Danger Risk',
    report_obstacle: 'Lambi Thiba Report',
    simulate_red_alert: 'Red Alert Simulation',
    reset_alert: 'Alert Reset',
    audio_broadcast: 'Voice Alert Broadcast',
    online_satellite: 'Network: Active',
    offline_mode: 'Offline Saved',
    origin: 'Houfam Hub',
    destination: 'Youfam Hub',
    calculate_route: 'Lambi Thirou',
    speed: 'Speed',
    temp: 'Medicine Temp',
    driver: 'Driver',
    cargo: 'Potlam',
    sos_trigger: 'SOS Emergency Alert',
    verified: 'Verified Official',
    disaster_active: 'Emergency Red Alert Active Across Manipur & NER',
    sync_now: 'Offline Sync',
    command_modules: 'Command Modules',
    active_fleets: 'Gari Chatliba',
    deficit_districts: 'Awatpa District'
  },
  lus: {
    app_title: 'LOGAINER',
    app_subtitle: 'North Eastern Region Tan AI Logistics & Kawng Dinhmun Platform',
    gis_map: 'GIS Map Enna',
    route_planner: 'AI Kawng Ruahmanna',
    fleet_telemetry: 'Motor Kal Lai Enna',
    district_health: 'District Inbiakpawhna Index',
    incident_reporter: 'Kawng Chhia Report-na',
    ml_risk_lab: 'Leimin Enlawkna AI',
    disaster_mode: 'Chhiatrupna Emergency Mode',
    analytics_reports: 'Sorkar Report',
    all_states: 'NER State 8 Te',
    active_convoys: 'Motor Kal Mek',
    chokepoints_blocked: 'Kawng Ping',
    avg_dci: 'Inzawmna Index',
    ai_risk_status: 'Hlauhawm Dinhmun',
    report_obstacle: 'Kawng Ping Report Rawh',
    simulate_red_alert: 'Red Alert Hawnna',
    reset_alert: 'Alert Titawp Rawh',
    audio_broadcast: 'Aw Ka Hmanga Hriattirna',
    online_satellite: 'Network: A Tha',
    offline_mode: 'Offline A Vawng Tha',
    origin: 'Chhuahna Hmun',
    destination: 'Thlenna Hmun',
    calculate_route: 'Kawng En Rawh',
    speed: 'Chak Zawng',
    temp: 'Damdawi Lum Zawng',
    driver: 'Khalhtu',
    cargo: 'Phurh Hnawm',
    sos_trigger: 'SOS Hmanhmawh Thawh Rawh',
    verified: 'Fiahna Nei',
    disaster_active: 'NER Kawng Puiah Hian Red Alert Puan A Ni',
    sync_now: 'Data Sync Rawh',
    command_modules: 'Hna thawh turte',
    active_fleets: 'Motor Kal Mekte',
    deficit_districts: 'Tlachham District-te'
  },
  brx: {
    app_title: 'LOGAINER',
    app_subtitle: 'सानजा-सोनाब ओनसोलनि थाखाय AI लामा आरो साबसिन रां-राथाइ राहा',
    gis_map: 'GIS मानसिथ्रा',
    route_planner: 'AI लामा दिन्थिग्रा',
    fleet_telemetry: 'गाड़ि थांनाय नायगिर',
    district_health: 'जिला फोनांजाब जुजि',
    incident_reporter: 'लामा जाब्रबनाय फोरमाय',
    ml_risk_lab: 'हा सिनायनाय सिगां रां',
    disaster_mode: 'आफद इमार्जेंसी',
    analytics_reports: 'सोरखारि फोरमायथि',
    all_states: '८ सा-सानजा रायजोफोर',
    active_convoys: 'गाड़िफोर',
    chokepoints_blocked: 'लामा बन्द जानाय',
    avg_dci: 'गोरोबनाय जुजि',
    ai_risk_status: 'AI खैफोद',
    report_obstacle: 'लामा बन्द फोरमाय',
    simulate_red_alert: 'रेड एलार्ट',
    reset_alert: 'एलार्ट फोजोब',
    audio_broadcast: 'रावजों सोंथि',
    online_satellite: 'नेटवर्क: दं',
    offline_mode: 'अफलाइन लाखिनाय',
    origin: 'ओंखारनाय जायगा',
    destination: 'सौहैनाय जायगा',
    calculate_route: 'लामा दिहुन',
    speed: 'गोख्रैथि',
    temp: 'उष्णता',
    driver: 'सालायग्रा',
    cargo: 'मुवाफोर',
    sos_trigger: 'SOS इमार्जेंसी',
    verified: 'सोरखारि रोखा',
    disaster_active: 'सा-सानजा लामायाव रेड एलार्ट जाबाय',
    sync_now: 'सिंक खालाम',
    command_modules: 'कमान्ड मडुल',
    active_fleets: 'सक्रिय गाड़िफोर',
    deficit_districts: 'खाहा जानाय जिलाफोर'
  },
  kha: {
    app_title: 'LOGAINER',
    app_subtitle: 'Ka AI Platform na ka bynta ka Kit ka Bah bad ka Leit ka Wan ha Shatei Lam Mihngi',
    gis_map: 'Ka Map GIS',
    route_planner: 'Ka AI Wad Lad Sarok',
    fleet_telemetry: 'Ka Jingbud ia ki Kali',
    district_health: 'Ka Index Jingiasoh ki District',
    incident_reporter: 'Ka Jingai Khubor Sarok Sahkut',
    ml_risk_lab: 'Ka Jingiathuh Lpa ia ka Twad Khyndew',
    disaster_mode: 'Ka Emergency ha ka Jingjia Ba Lanwir',
    analytics_reports: 'Ka Kaiphod Sorkar',
    all_states: 'Kiba 8 Tylli ki Jylla NER',
    active_convoys: 'Ki Kali ba Dang Iaid',
    chokepoints_blocked: 'Ki Sarok ba la Sahkut',
    avg_dci: 'Ka Index Jingiasoh',
    ai_risk_status: 'Ka AI Jingma',
    report_obstacle: 'Ai Khubor Sarok Dkut',
    simulate_red_alert: 'Pynmih Red Alert',
    reset_alert: 'Pynlip ia ka Alert',
    audio_broadcast: 'Ka Khubor da ka Sur Kren',
    online_satellite: 'Network: Don',
    offline_mode: 'Offline la Kynshew',
    origin: 'Khyndew ba Mih',
    destination: 'Ka Hmun ba Thmu ban Poi',
    calculate_route: 'Wad Sarok ba Bha',
    speed: 'Ka Jingstet',
    temp: 'Ka Jingkhriat Dawai',
    driver: 'U Nongniah',
    cargo: 'Ka Mar ba Kit',
    sos_trigger: 'Pyrta SOS Emergency',
    verified: 'La Pynskhem da ka Sorkar',
    disaster_active: 'Ka Red Alert ha ki Sarokbah jong ka NER',
    sync_now: 'Sync ia ki Khubor',
    command_modules: 'Ki Module Pyniaid',
    active_fleets: 'Ki Kali ba Iaid',
    deficit_districts: 'Ki District ba Duna Mar'
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  speakAlert: (text: string) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>('en');

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;
  };

  const speakAlert = (text: string) => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 0.92;
      utterance.pitch = 1.0;
      
      const langCodeMap: Record<string, string> = {
        ta: 'ta-IN',
        te: 'te-IN',
        kn: 'kn-IN',
        ml: 'ml-IN',
        mr: 'mr-IN',
        hi: 'hi-IN',
        bn: 'bn-IN',
        en: 'en-IN',
        as: 'as-IN'
      };

      utterance.lang = langCodeMap[language] || 'en-IN';

      const voices = window.speechSynthesis.getVoices();
      const match = voices.find(v => v.lang.startsWith(language) || v.lang === langCodeMap[language] || (v.lang.includes('IN') && (language === 'ta' ? v.lang.includes('ta') : true)));
      if (match) utterance.voice = match;

      window.speechSynthesis.speak(utterance);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, speakAlert }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
